config/routes.rb
Qa::Engine.routes.draw do
  resources :talks do
  end
  resources :tasks do
    collection do
        get 'search'
    end
  end
  resources :themes do
    resources :tasks do
      member do
        get 'archive'
        get 'done'
      end
    end
  end
  resources :posts
  resources :categories
  root 'home#pannel'
  get 'home/pannel'
end

app/models/qa/application_record.rb
module Qa
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/qa/category.rb
module Qa
  class Category < ApplicationRecord
  end
end

app/models/qa/post.rb
module Qa
  class Post < ApplicationRecord
  end
end

app/models/qa/talk.rb
module Qa
  class Talk < ApplicationRecord
    belongs_to :user, class_name: 'User'
    belongs_to :task
    has_rich_text :content

    delegate :name, to: :user, prefix: true

    def content_modifier
      self.content.to_s.gsub('/qa/rails/active_', '/rails/active_').html_safe
    end

  end
end

app/models/qa/task.rb
module Qa
  class Task < ApplicationRecord
    belongs_to :theme
    has_many :talks
    belongs_to :user, class_name: 'User'
    delegate :name, to: :user, prefix: true
    validates :name, presence: true

    enum status: {
      todo: 0,
      done: 1,
      archived: 2
    }


    def talk_contents
      talks.map { |talk|
        "<div class='qa-talk-wrap'>" + \
        talk.content_modifier + \
          "<div class='qa-talk-user'><h5>#{talk.user_name} @ <span>#{talk.created_at.to_s(:short)}</span></h5></div></div>".html_safe
      }.join.html_safe
    end

    def css_class(current_task)
      names = []
      if current_task == self
        names << 'qa-current-task'
      end
      names << "qa-status-#{self.status}"
      names.join(' ')
    end

  end
end

app/models/qa/theme.rb
module Qa
  class Theme < ApplicationRecord
    has_many :tasks
    belongs_to :user, class_name: 'User'
    delegate :name, to: :user, prefix: true
    validates :name, presence: true

    def all_done_tasks
      Task.where(theme_id: self.id, status: :done).order(updated_at: 'DESC')
    end
    def all_todo_tasks
      Task.where(theme_id: self.id, status: :todo).order(updated_at: 'DESC')
    end
  end
end

app/controllers/qa/application_controller.rb
module Qa
  class ApplicationController < Qa.main_controller
    protect_from_forgery with: :exception
    before_action :set_current_user

    private
    def set_current_user
      @current_user = current_user
    end

  end
end

app/controllers/qa/categories_controller.rb
# frozen_string_literal: true

require_dependency 'qa/application_controller'

module Qa
  # Category
  class CategoriesController < ApplicationController
    before_action :set_category, only: %i[show edit update destroy]

    # GET /categories
    def index
      @categories = Category.all
    end

    # GET /categories/1
    def show; end

    # GET /categories/new
    def new
      @category = Category.new
    end

    # GET /categories/1/edit
    def edit; end

    # POST /categories
    def create
      @category = Category.new(category_params)

      if @category.save
        redirect_to @category, notice: 'Category was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /categories/1
    def update
      if @category.update(category_params)
        redirect_to @category, notice: 'Category was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /categories/1
    def destroy
      @category.destroy
      redirect_to categories_url, notice: 'Category was successfully destroyed.'
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def category_params
      params.require(:category).permit(:name, :status, :user_ids)
    end
  end
end

app/controllers/qa/home_controller.rb
require_dependency "qa/application_controller"

module Qa
  class HomeController < ApplicationController
    def pannel
    end
  end
end

app/controllers/qa/posts_controller.rb
require_dependency "qa/application_controller"

module Qa
  class PostsController < ApplicationController
    # layout 'qa/application'
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    # GET /posts
    def index
      @posts = Post.all
    end

    # GET /posts/1
    def show
    end

    # GET /posts/new
    def new
      @post = Post.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts
    def create
      @post = Post.new(post_params)

      if @post.save
        redirect_to @post, notice: 'Post was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /posts/1
    def update
      if @post.update(post_params)
        redirect_to @post, notice: 'Post was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /posts/1
    def destroy
      @post.destroy
      redirect_to posts_url, notice: 'Post was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def post_params
        params.require(:post).permit(:name, :content, :user_id, :status)
      end
  end
end

app/controllers/qa/talks_controller.rb
require_dependency "qa/application_controller"

module Qa
  class TalksController < ApplicationController
    before_action :set_talk, only: [:show, :edit, :update, :destroy]

    # GET /talks
    def index
      @talks = Talk.all
    end

    # GET /talks/1
    def show
    end

    # GET /talks/new
    def new
      @talk = Talk.new
    end

    # GET /talks/1/edit
    def edit
    end

    # POST /talks
    def create
      @talk = Talk.new(talk_params)
      @task = Task.find talk_params[:task_id]

      if @talk.save
        # render js: 'alert("hi")'
      else
        render js: 'alert("Error")'
      end
    end

    # PATCH/PUT /talks/1
    def update
      if @talk.update(talk_params)
        redirect_to @talk, notice: 'Talk was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /talks/1
    def destroy
      @talk.destroy
      redirect_to talks_url, notice: 'Talk was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_talk
        @talk = Talk.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def talk_params
        params.require(:talk).permit(:content, :user_id, :task_id)
      end
  end
end

app/controllers/qa/tasks_controller.rb
require_dependency "qa/application_controller"

module Qa
  class TasksController < ApplicationController
    before_action :set_task, only: [:show, :edit, :update, :destroy, :done]
    before_action :set_theme
    skip_before_action :set_theme, only: [:search]

    # GET /tasks
    def index
      @tasks = Task.all
    end

    def search
      @tasks = Task.where('name like ?', "%#{params[:content]}%")
    end

    # GET /tasks/1
    def show
      @talk = Talk.new
    end

    def done
      @task.done!
      url = theme_task_url(@theme, @task)
      ActiveSupport::Notifications.instrument "qa.task.done", task: @task, url: url
      redirect_to url
    end

    # GET /tasks/new
    def new
      @task = Task.new
    end

    # GET /tasks/1/edit
    def edit
    end

    # POST /tasks
    def create
      @task = Task.new(task_params)
      @task.theme_id = @theme.id
      @task.user_id = current_user.id

      if @task.save
        url = theme_task_url(@theme, @task)
        ActiveSupport::Notifications.instrument "qa.task.created", task: @task, url: url
        redirect_to theme_task_url(@theme, @task), notice: 'Task was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /tasks/1
    def update
      if @task.update(task_params)
        redirect_to @task, notice: 'Task was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /tasks/1
    def destroy
      @task.destroy
      redirect_to tasks_url, notice: 'Task was successfully destroyed.'
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def set_theme
      @theme = Theme.find(params[:theme_id])
    end
    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:name, :deadline, :tag_ids, :user_id)
    end
  end
end

app/controllers/qa/themes_controller.rb
require_dependency "qa/application_controller"

module Qa
  class ThemesController < ::Qa::ApplicationController
    # layout 'qa/application'
    before_action :set_theme, only: [:show, :edit, :update, :destroy]

    # GET /themes
    def index
      @themes = Theme.all
    end

    # GET /themes/1
    def show
    end

    # GET /themes/new
    def new
      @theme = Theme.new
    end

    # GET /themes/1/edit
    def edit
    end

    # POST /themes
    def create
      @theme = Theme.new(theme_params)
      @theme.user_id = current_user.id

      if @theme.save
        redirect_to @theme, notice: 'Theme was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /themes/1
    def update
      if @theme.update(theme_params)
        redirect_to @theme, notice: 'Theme was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /themes/1
    def destroy
      @theme.destroy
      redirect_to themes_url, notice: 'Theme was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_theme
        @theme = Theme.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def theme_params
        params.require(:theme).permit(:name, :user_id, :user_ids)
      end
  end
end

app/helpers/qa/application_helper.rb
require "webpacker/helper"

module Qa
  module ApplicationHelper
    include ::Webpacker::Helper

    def test_tag
      binding.pry
      'Hello World'
    end

    def current_webpacker_instance
      Qa.webpacker
    end
  end
end

app/helpers/qa/categories_helper.rb
module Qa
  module CategoriesHelper
  end
end

app/helpers/qa/home_helper.rb
module Qa
  module HomeHelper
  end
end

app/helpers/qa/posts_helper.rb
module Qa
  module PostsHelper
  end
end

app/helpers/qa/talks_helper.rb
module Qa
  module TalksHelper
  end
end

app/helpers/qa/tasks_helper.rb
module Qa
  module TasksHelper
  end
end

app/helpers/qa/themes_helper.rb
require "webpacker/helper"
module Qa
  module ThemesHelper
    include ::Webpacker::Helper
    def current_webpacker_instance
      Qa.webpacker
    end
    def ttest
      'hi'
    end
  end
end

app/views/qa/themes/_form.html.erb
<%= form_with(model: theme, local: true) do |form| %>
  <% if theme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(theme.errors.count, "error") %> prohibited this theme from being saved:</h2>

      <ul>
        <% theme.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, autofocus: true %>
  </div>

    <%= form.hidden_field :user_id, value: @current_user.id %>

  <div class="actions">
    <%= form.submit '提交', class: 'btn btn-info' %>
  </div>
<% end %>

app/views/qa/themes/edit.html.erb
<h1>Editing Theme</h1>

<%= render 'form', theme: @theme %>

<%= link_to 'Show', @theme %> |
<%= link_to 'Back', themes_path %>

app/views/qa/themes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Themes</h1>
<%= ttest %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>User ids</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @themes.each do |theme| %>
      <tr>
        <td><%= theme.name %></td>
        <td><%= theme.user_id %></td>
        <td><%= theme.user_ids %></td>
        <td><%= link_to 'Show', theme %></td>
        <td><%= link_to 'Edit', edit_theme_path(theme) %></td>
        <td><%= link_to 'Destroy', theme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Theme', new_theme_path %>

app/views/qa/themes/new.html.erb
<h1>
    新增项目
</h1>

<%= render 'form', theme: @theme %>

app/views/qa/themes/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
    <%= @theme.name %>
</h1>
<h4>
    负责人:     <%= @theme.user_name %>
</h4>

<% if @theme.present? && @theme.id %>
    <div class="m-auto qa-actions">
        <%= link_to new_theme_task_path(@theme), class: "btn btn-primary btn-lg btn-block" do %>
            <i class='fas fa-plus'></i> 任务
        <% end %>
    </div>

    <br />

    <div class='qa-list container-fluid'>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">任务</th>
                    <th scope="col">创建时间</th>
                    <th scope="col">截止时间</th>
                </tr>
            </thead>
            <tbody>

        <% @theme.all_todo_tasks.each_with_index do |task, i| %>
            <tr>
                <td>
                    <%= i+1 %>
                </td>
                <td>
                    <%=link_to(theme_task_path(@theme, task),
                        class: task.css_class(@task)
                    ) do %>
                        <i class="fas fa-project-diagram"></i>
                        <%= task.name %>
                    <% end %>

                </td>
                <td>
                    <%= task.created_at.to_s(:short) %>
                </td>
                <td>
                    <%= task.deadline %>
                </td>
            </tr>
            
        <% end %>
            </tbody>
        </table>

        <hr />

        <% @theme.all_done_tasks.each do |task| %>
            <%=link_to(
                theme_task_path(@theme, task),
                class: task.css_class(@task)
            ) do %>
                <i class="fas fa-archive"></i>
                <%= task.name %>
            <% end %>
        <% end %>
    </div>
<% end %>